name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  release-client:
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create_release.outputs.url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read version from versions.yml
        id: read_version
        run: |
          # Read major and minor versions from versions.yml
          MAJOR=$(grep 'major:' versions.yml | awk '{print $2}')
          MINOR=$(grep 'minor:' versions.yml | awk '{print $2}')

          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MINOR" >> $GITHUB_ENV
          echo "Using major version: $MAJOR, minor version: $MINOR from versions.yml"

      - name: Get Latest Release
        id: get_latest_release
        run: |
          # Read major and minor versions from environment
          MAJOR="${{ env.MAJOR }}"
          MINOR="${{ env.MINOR }}"

          # Get all releases using GitHub API
          RELEASES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases" | \
            grep '"tag_name":' | \
            sed -E 's/.*"([^"]+)".*/\1/')

          # Initialize variables
          LATEST_PATCH=-1
          LATEST_RELEASE="v0.0.0"
          IS_FIRST_RELEASE=false

          # Process each release to find the highest patch for the specified major.minor
          if [ -n "$RELEASES" ]; then
            while read -r release; do
              # Remove 'v' prefix if it exists
              VERSION=${release#v}

              # Split version into components
              IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"

              # Check if this release matches our major and minor versions
              if [ "${VERSION_PARTS[0]}" = "$MAJOR" ] && [ "${VERSION_PARTS[1]}" = "$MINOR" ]; then
                # Check if this patch is higher than what we've seen so far
                if [ "${VERSION_PARTS[2]}" -gt "$LATEST_PATCH" ]; then
                  LATEST_PATCH=${VERSION_PARTS[2]}
                  LATEST_RELEASE=$release
                fi
              fi
            done <<< "$RELEASES"
          fi

          # If no matching releases exist, start with v{major}.{minor}.0
          if [ "$LATEST_PATCH" -eq -1 ]; then
            LATEST_RELEASE="v${MAJOR}.${MINOR}.0"
            IS_FIRST_RELEASE=true
            echo "No previous releases found for v${MAJOR}.${MINOR}.*. Starting with $LATEST_RELEASE"
          else
            echo "Latest release for v${MAJOR}.${MINOR}.*: $LATEST_RELEASE"
          fi

          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          echo "IS_FIRST_RELEASE=$IS_FIRST_RELEASE" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        run: |
          # Remove 'v' prefix if it exists
          VERSION=${LATEST_RELEASE#v}

          # Split version into components to get the patch version
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"

          # Check if this is the first release
          if [ "${{ env.IS_FIRST_RELEASE }}" = "true" ]; then
            # Don't increment patch version for the first release
            PATCH=${VERSION_PARTS[2]}
            echo "First release detected, not incrementing patch version"
          else
            # Increment patch version for subsequent releases
            PATCH=$((VERSION_PARTS[2] + 1))
            echo "Subsequent release detected, incrementing patch version"
          fi

          # Create new version using major and minor from versions.yml
          NEW_VERSION="v${{ env.MAJOR }}.${{ env.MINOR }}.$PATCH"
          echo "New version: $NEW_VERSION"

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
          generate_release_notes: true
          make_latest: true
          files: release.txt

      - name: Print Release URL
        run: |
          echo "::notice::New release created: ${{ steps.create_release.outputs.url }}"

  release-site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: release-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: site/package-lock.json

      - name: Install Dependencies
        working-directory: ./site
        run: npm ci

      - name: Build Site
        working-directory: ./site
        env:
          REACT_APP_RELEASE_URL: ${{ needs.create_release.outputs.release_url }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/build/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Print Published Site URL
        run: |
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          SITE_URL="https://$REPO_OWNER.github.io/$REPO_NAME/"
          echo "::notice::Published site is available at: $SITE_URL"
