name: Release Site

on:
  workflow_run:
    workflows: ["Release App"]
    types:
      - completed

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Release URL
        id: get_release_url
        run: |
          # Get the latest release URL
          # We're using the GitHub API to get the latest release since we can't directly access
          # the outputs from the previous workflow in a workflow_run trigger
          RELEASE_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
            jq -r '.html_url')
          echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV
          echo "Release URL: $RELEASE_URL"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        working-directory: ./site
        run: npm ci

      - name: Build Site
        working-directory: ./site
        env:
          REACT_APP_RELEASE_URL: ${{ env.RELEASE_URL }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site/build
          branch: gh-pages
          clean: true